"""Add absolute/relative cashback and points fields to ShopProgramRate for v0.2.4

Revision ID: 5bc508a33a3f
Revises: v0_2_3
Create Date: 2026-01-14 09:12:47.275860

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5bc508a33a3f"
down_revision: str | Sequence[str] | None = "v0_2_3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bonus_programs", "description")
    op.alter_column(
        "contributor_requests",
        "status",
        existing_type=sa.VARCHAR(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "coupons",
        "status",
        existing_type=sa.VARCHAR(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "notifications",
        "is_read",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "proposal_votes",
        "vote_weight",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("proposal_votes_proposal_id_voter_id_key"), "proposal_votes", type_="unique"
    )
    op.create_unique_constraint(
        "unique_proposal_voter", "proposal_votes", ["proposal_id", "voter_id"]
    )
    op.alter_column(
        "proposals",
        "status",
        existing_type=sa.VARCHAR(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "proposals",
        "source",
        existing_type=sa.VARCHAR(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "proposals",
        "approved_by_system",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_scheduled_job_runs_scheduled_job_id"), table_name="scheduled_job_runs")
    op.drop_constraint(op.f("scheduled_jobs_job_name_key"), "scheduled_jobs", type_="unique")
    op.alter_column(
        "shop_main",
        "status",
        existing_type=sa.VARCHAR(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "shop_merge_proposals",
        "status",
        existing_type=sa.VARCHAR(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "shop_metadata_proposals",
        "status",
        existing_type=sa.VARCHAR(),
        server_default=None,
        existing_nullable=False,
    )
    op.add_column("shop_program_rates", sa.Column("points_absolute", sa.Float(), nullable=True))
    op.add_column("shop_program_rates", sa.Column("cashback_absolute", sa.Float(), nullable=True))
    op.add_column("shop_program_rates", sa.Column("rate_note", sa.String(), nullable=True))
    op.alter_column(
        "shop_program_rates",
        "points_per_eur",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "shop_program_rates",
        "cashback_pct",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "shop_variants",
        "confidence_score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=None,
        existing_nullable=True,
    )
    op.drop_constraint(op.f("shop_variants_source_source_id_key"), "shop_variants", type_="unique")
    op.create_unique_constraint(
        "unique_shop_variant", "shop_variants", ["shop_main_id", "source", "source_id"]
    )
    op.alter_column(
        "users", "role", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "users", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "status",
        existing_type=sa.VARCHAR(),
        server_default=sa.text("'active'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(),
        server_default=sa.text("'viewer'::character varying"),
        existing_nullable=False,
    )
    op.drop_constraint("unique_shop_variant", "shop_variants", type_="unique")
    op.create_unique_constraint(
        op.f("shop_variants_source_source_id_key"),
        "shop_variants",
        ["source", "source_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "shop_variants",
        "confidence_score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=sa.text("'100'::double precision"),
        existing_nullable=True,
    )
    op.alter_column(
        "shop_program_rates",
        "cashback_pct",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=sa.text("'0'::double precision"),
        existing_nullable=True,
    )
    op.alter_column(
        "shop_program_rates",
        "points_per_eur",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=sa.text("'0'::double precision"),
        existing_nullable=True,
    )
    op.drop_column("shop_program_rates", "rate_note")
    op.drop_column("shop_program_rates", "cashback_absolute")
    op.drop_column("shop_program_rates", "points_absolute")
    op.alter_column(
        "shop_metadata_proposals",
        "status",
        existing_type=sa.VARCHAR(),
        server_default=sa.text("'PENDING'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "shop_merge_proposals",
        "status",
        existing_type=sa.VARCHAR(),
        server_default=sa.text("'PENDING'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "shop_main",
        "status",
        existing_type=sa.VARCHAR(),
        server_default=sa.text("'active'::character varying"),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        op.f("scheduled_jobs_job_name_key"),
        "scheduled_jobs",
        ["job_name"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_scheduled_job_runs_scheduled_job_id"),
        "scheduled_job_runs",
        ["scheduled_job_id"],
        unique=False,
    )
    op.alter_column(
        "proposals",
        "approved_by_system",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=True,
    )
    op.alter_column(
        "proposals",
        "source",
        existing_type=sa.VARCHAR(),
        server_default=sa.text("'user'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "proposals",
        "status",
        existing_type=sa.VARCHAR(),
        server_default=sa.text("'pending'::character varying"),
        existing_nullable=False,
    )
    op.drop_constraint("unique_proposal_voter", "proposal_votes", type_="unique")
    op.create_unique_constraint(
        op.f("proposal_votes_proposal_id_voter_id_key"),
        "proposal_votes",
        ["proposal_id", "voter_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "proposal_votes",
        "vote_weight",
        existing_type=sa.INTEGER(),
        server_default=sa.text("1"),
        existing_nullable=False,
    )
    op.alter_column(
        "notifications",
        "is_read",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "coupons",
        "status",
        existing_type=sa.VARCHAR(),
        server_default=sa.text("'active'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "contributor_requests",
        "status",
        existing_type=sa.VARCHAR(),
        server_default=sa.text("'pending'::character varying"),
        existing_nullable=False,
    )
    op.add_column(
        "bonus_programs", sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
