"""Add rate_type to ShopProgramRate

Revision ID: 6673d6fd0159
Revises: 5bc508a33a3f
Create Date: 2026-01-21 12:09:17.363487

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6673d6fd0159"
down_revision: str | Sequence[str] | None = "5bc508a33a3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first to handle existing data
    op.add_column("shop_program_rates", sa.Column("rate_type", sa.String(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE shop_program_rates SET rate_type = 'shop' WHERE rate_type IS NULL")
    # Now make it non-nullable
    op.alter_column("shop_program_rates", "rate_type", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shop_program_rates", "rate_type")
    # ### end Alembic commands ###
